
import { AppSettings, Language } from './types.ts';

export const SYSTEM_CONFIG = {
  API_URL: "https://script.google.com/macros/s/AKfycbxN5It2eczVQ1oL0uE9cjEC8sqKITOMKJdl9_jMx7Z7taFNdEMb5LdyjErhARNHno4JXA/exec",
  SHEET_URL: "https://docs.google.com/spreadsheets/d/1_85YEZSQFARb7HgA2hfNOj4bxoptdjqQfAqq3Y0uY9o/edit"
};

export const DEFAULT_SETTINGS: AppSettings = {
  decimals: 2,
  minLen: 4,
  maxLen: 50,
  filenameFormat: "USER_YYYYMMDDHHmmss"
};

export const TRANSLATIONS = {
  'zh-TW': {
    appTitle: "Extrusion Inventory v3",
    user: "人員 (User)",
    cycleCount: "盤點 (No.)",
    count1: "1️⃣ 盤點 1 (H欄)",
    count2: "2️⃣ 盤點 2 (I欄)",
    count3: "3️⃣ 盤點 3 (J欄)",
    count4: "4️⃣ 盤點 4 (K欄)",
    count5: "5️⃣ 盤點 5 (L欄)",
    modeBarcode: "條碼/QR",
    modeBarcodeSub: "Barcode & QR",
    modeOCR: "文字識別",
    modeOCRSub: "OCR Text",
    clear: "清除",
    settings: "設定",
    flash: "補光燈",
    flashOff: "關閉補光燈",
    export: "匯出",
    openSheet: "開啟試算表",
    upload: "上傳資料",
    tableCode: "唯一碼 (Code)",
    tableLoc: "儲位",
    tableName: "品名",
    tableQty: "平均",
    tableAct: "操作",
    noData: "暫無資料 (No Data)",
    confirmCode: "1️⃣ 確認條碼 (Code):",
    confirmName: "2️⃣ 品名 (Name):",
    confirmQty: "3️⃣ 數量 (Qty):",
    confirmLoc: "4️⃣ 儲位 (Location):",
    tooShort: "❌ 太短 (Min: ",
    tooLong: "❌ 太長 (Max: ",
    deleteConfirm: "刪除項目 (Delete): ",
    clearFieldConfirm: "清除此欄位數值? ",
    clearAllConfirm: "清除所有資料? (Clear All?)",
    uploadConfirm: "上傳至雲端?\n\n⚠️ 此操作將覆蓋雲端上相同唯一碼的所有欄位資料 (包含主數量與所有盤點欄位)。\n\n是否繼續？",
    uploadSuccess: "✅ 上傳成功",
    uploadFail: "❌ 上傳失敗: ",
    exportSuccess: "✅ 匯出完成",
    settingsTitle: "⚙️ 系統設定",
    decLabel: "小數點位數 (Decimal):",
    minLabel: "最少辨識字元 (Min):",
    maxLabel: "最大辨識字元 (Max):",
    fileFmtLabel: "匯出檔名格式:",
    save: "儲存",
    cancel: "取消",
    scannerStart: "👆 點擊畫面開始掃描",
    scannerClick: "",
    ocrProcessing: "處理中...",
    ocrReady: "✅ 識別就緒",
    ocrWait: "👀 掃描中... 請對準文字",
    ocrTap: "👆 點擊畫面抓取",
    langSelect: "選擇語言 (Select Language)",
    editPrompt: "輸入數值 (Enter Value):",
    authChecking: "正在驗證權限...",
    authDeniedTitle: "存取被拒 (Access Denied)",
    authDeniedMsg: "您無權限使用此系統，請申請 Google Sheet 編輯者權限。",
    authRetry: "重新驗證",
    scanDetected: "🔍 已偵測：",
    scanConfirm: "(再次點擊畫面確認)",
    scanHint: "👀 掃描中... 請對準目標"
  },
  'en': {
    appTitle: "Extrusion Inventory v3",
    user: "User",
    cycleCount: "Cycle Count",
    count1: "1️⃣ Count 1 (Col H)",
    count2: "2️⃣ Count 2 (Col I)",
    count3: "3️⃣ Count 3 (Col J)",
    count4: "4️⃣ Count 4 (Col K)",
    count5: "5️⃣ Count 5 (Col L)",
    modeBarcode: "Barcode/QR",
    modeBarcodeSub: "Scan Code",
    modeOCR: "OCR Text",
    modeOCRSub: "Recognize Text",
    clear: "Clear",
    settings: "Settings",
    flash: "Flash",
    flashOff: "Flash Off",
    export: "Export",
    openSheet: "Open Sheet",
    upload: "Upload Data",
    tableCode: "Code",
    tableLoc: "Loc",
    tableName: "Name",
    tableQty: "Avg",
    tableAct: "Action",
    noData: "No Data",
    confirmCode: "1️⃣ Confirm Code:",
    confirmName: "2️⃣ Name:",
    confirmQty: "3️⃣ Quantity:",
    confirmLoc: "4️⃣ Location:",
    tooShort: "❌ Too short (Min: ",
    tooLong: "❌ Too long (Max: ",
    deleteConfirm: "Delete Item: ",
    clearFieldConfirm: "Clear value for field? ",
    clearAllConfirm: "Clear All Data?",
    uploadConfirm: "Upload to cloud?\n\n⚠️ This will overwrite existing data for these codes on the cloud.\n\nContinue?",
    uploadSuccess: "✅ Upload Success",
    uploadFail: "❌ Upload Failed: ",
    exportSuccess: "✅ Export Done",
    settingsTitle: "⚙️ System Settings",
    decLabel: "Decimals:",
    minLabel: "Min Length:",
    maxLabel: "Max Length:",
    fileFmtLabel: "Filename Format:",
    save: "Save",
    cancel: "Cancel",
    scannerStart: "👆 Tap to Start Scan",
    scannerClick: "",
    ocrProcessing: "Processing...",
    ocrReady: "✅ Ready",
    ocrWait: "👀 Scanning... Align Text",
    ocrTap: "👆 Tap to Capture",
    langSelect: "Select Language",
    editPrompt: "Enter Value:",
    authChecking: "Checking Permissions...",
    authDeniedTitle: "Access Denied",
    authDeniedMsg: "You do not have permission. Please request Google Sheet Editor access.",
    authRetry: "Retry",
    scanDetected: "🔍 Detected: ",
    scanConfirm: "(Tap again to confirm)",
    scanHint: "👀 Scanning... Align Code"
  },
  'hi': {
    appTitle: "मिक्सिंग इन्वेंटरी",
    user: "उपयोगकर्ता (User)",
    cycleCount: "साइकिल गिनती (No.)",
    count1: "1️⃣ गिनती 1 (Col H)",
    count2: "2️⃣ गिनती 2 (Col I)",
    count3: "3️⃣ गिनती 3 (Col J)",
    count4: "4️⃣ गिनती 4 (Col K)",
    count5: "5️⃣ गिनती 5 (Col L)",
    modeBarcode: "बारकोड/QR",
    modeBarcodeSub: "Scan Code",
    modeOCR: "टेक्स्ट स्कैन (OCR)",
    modeOCRSub: "Recognize Text",
    clear: "साफ़ करें",
    settings: "सेटिंग्स",
    flash: "फ्लैश",
    flashOff: "फ्लैश बंद",
    export: "निर्यात (Export)",
    openSheet: "शीट खोलें",
    upload: "डेटा अपलोड",
    tableCode: "कोड",
    tableLoc: "स्थान",
    tableName: "नाम",
    tableQty: "औसत",
    tableAct: "क्रिया",
    noData: "कोई डेटा नहीं (No Data)",
    confirmCode: "1️⃣ कोड की पुष्टि करें:",
    confirmName: "2️⃣ नाम:",
    confirmQty: "3️⃣ मात्रा (Qty):",
    confirmLoc: "4️⃣ स्थान (Location):",
    tooShort: "❌ बहुत छोटा (Min: ",
    tooLong: "❌ बहुत लंबा (Max: ",
    deleteConfirm: "हटाएं (Delete): ",
    clearFieldConfirm: "इस मान को साफ़ करें? ",
    clearAllConfirm: "सारा डेटा साफ़ करें?",
    uploadConfirm: "क्लाउड पर अपलोड करें?\n\n⚠️ यह क्लाउड पर मौजूद डेटा को अधिलेखित (overwrite) कर देगा।\n\nजारी रखें?",
    uploadSuccess: "✅ अपलोड सफल",
    uploadFail: "❌ अपलोड विफल: ",
    exportSuccess: "✅ निर्यात पूर्ण",
    settingsTitle: "⚙️ सेटिंग्स",
    decLabel: "दशमलव (Decimals):",
    minLabel: "न्यूनतम लंबाई:",
    maxLabel: "अधिकतम लंबाई:",
    fileFmtLabel: "फाइल नाम प्रारूप:",
    save: "सहेजें",
    cancel: "रद्द करें",
    scannerStart: "👆 स्कैन शुरू करने के लिए टै平 करें",
    scannerClick: "",
    ocrProcessing: "प्रक्रिया जारी है...",
    ocrReady: "✅ तैयार",
    ocrWait: "👀 टेक्स्ट संरेखित करें",
    ocrTap: "👆 कैप्चर करें",
    langSelect: "भाषा चुनें (Select Language)",
    editPrompt: "मान दर्ज करें (Enter Value):",
    authChecking: "अनुमतियों की जाँच...",
    authDeniedTitle: "पहुँच अस्वीकृत",
    authDeniedMsg: "आपके पास अनुमति नहीं है। कृपया संपादक (Editor) पहुँच का अनुरोध करें।",
    authRetry: "पुनः प्रयास करें",
    scanDetected: "🔍 पता चला: ",
    scanConfirm: "(पुष्टि करने के लिए फिर से टैप करें)",
    scanHint: "👀 स्कैनिंग... कोड संरेखित करें"
  }
};
